#!/bin/sh

# Load custom liftsh config
if test -f ~/.liftsh.config; then
  . ~/.liftsh.config
fi

# Default option if nothing is specified
DEFAULT_OPTS="-Xmx1g -noverify -XX:+CMSClassUnloadingEnabled -XX:MaxPermSize=256M -Dsbt.intransitive=true"

exec java ${LIFTSH_OPTS:-${DEFAULT_OPTS}} -jar `dirname $0`/project/sbt-launch-0.7.5.RC0.jar "$@"
